# -*- coding: utf-8 -*-
"""ML Pratical-4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Gl24HzbEJnYMhiDX-PC1KfK2ewyVc8fy
"""

# importing required libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# reading csv file and extracting class column to y.
x = pd.read_csv("cancer.csv")
a = np.array(x)
y = a[:,30] # classes having 0 and 1

# extracting two features
x = np.column_stack((x.State))

# 569 samples and 2 features
x.shape

print (x),(y)